# Generated by Django 5.0.2 on 2024-05-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Mothers_Name', models.CharField(max_length=30)),
                ('Fathers_Name', models.CharField(max_length=30)),
                ('Address', models.TextField(max_length=200)),
                ('Contact1', models.PositiveBigIntegerField()),
                ('Contact2', models.PositiveBigIntegerField()),
                ('Class_10', models.FloatField()),
                ('Class_12', models.FloatField()),
                ('UG_CGPA', models.FloatField()),
                ('Course', models.CharField(max_length=100)),
                ('Photograph', models.ImageField(upload_to='')),
                ('Signature', models.ImageField(upload_to='')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.stu_details')),
            ],
        ),
    ]
