# Generated by Django 5.0.2 on 2024-05-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applications',
            new_name='applicationss',
        ),
    ]
