# Generated by Django 5.0.2 on 2024-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_applications_applicationss'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationss',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
