# Generated by Django 5.0.2 on 2024-05-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_applicationss_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationss',
            name='status',
        ),
    ]
