# Generated by Django 5.0.2 on 2024-05-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0003_applicationss_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.applicationss', to_field='email')),
            ],
        ),
    ]
